apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gh-env-tidbcloud-lake-jdbc-maven-central-com-tidbcloud-release
  labels:
    ee.pingcap.com/owner-team: platform
    ee.pingcap.com/managed-by: fluxcd
    ee.pingcap.com/github-org: tidbcloud
spec:
  provider:
    github:
      appID: 214286
      installationID: 65036159
      organization: tidbcloud
      repository: lake-jdbc # current implementation assumes Maven release target repo is tidbcloud/lake-jdbc
      environment: maven-central-com-tidbcloud-release
      auth:
        privateKey:
          name: github-app-private-key
          key: privateKey.pem
