apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatops-lark
resources:
  - namespace.yaml
  - external-secret.yaml
  - external-secret-github.yaml
  - release-mcp-tool-github.yaml
  - release.yaml
