apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-src-lakesql-package-apk-public-key-b64
  labels:
    ee.pingcap.com/owner-team: platform
    ee.pingcap.com/managed-by: fluxcd
    ee.pingcap.com/github-org: tidbcloud
  annotations:
    ee.pingcap.com/source-secret-id: gha__env__tidbcloud__lakesql__release-s3__lakesql_package_apk_public_key_b64
    ee.pingcap.com/github-secret-name: LAKESQL_PACKAGE_APK_PUBLIC_KEY_B64
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-sm-github-actions
    kind: SecretStore
  target:
    name: src-lakesql-package-apk-public-key-b64
    creationPolicy: Owner
  data:
    - secretKey: value
      remoteRef:
        key: gha__env__tidbcloud__lakesql__release-s3__lakesql_package_apk_public_key_b64
