# Reference: https://flux-iac.github.io/tofu-controller/
# This Terraform CR creates a GCS bucket using the module in the same directory.
# Prerequisites:
#   1. GCP Workload Identity is configured (see tofu-controller/post/runner-workload-identity.yaml)
#   2. The GCP SA has roles/storage.admin permission
#   3. Update the spec.approvePlan when you're ready to apply
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: gcp-terraform
spec:
  approvePlan: auto
  interval: 1h
  retryInterval: 20s
  # Set to "auto" to auto-apply plans:
  # approvePlan: auto
  destroyResourcesOnDeletion: true
  path: ./infrastructure/gcp/terraform/resources
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
