apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - gcp-pingcap-testing-account.yaml
  - tencentcloud-tidb-cicd.yaml
  - tencentcloud-tidb-cicd-creds.yaml
