apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - helm-repo-bitnami-legacy.yaml
  - helm-repo-bitnami.yaml
  - helm-repo-ee-apps.yaml
  - helm-repo-ee-ops.yaml
  - helm-repo-external-secrets.yaml
  - helm-repo-kyverno.yaml
  - helm-repo-others.yaml
