apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: cd-publishing-requests
  labels:
    strimzi.io/cluster: cluster-cd
spec:
  partitions: 3
  replicationFactor: 2
  retention.ms: 604800000 # 7 days
  segment.bytes: 1073741824 # 1 GB
