apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: set-pod-node-selector
spec:
  rules:
    - name: add-compute-class-and-annotations
      match:
        resources:
          kinds:
            - Pod
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
          spec:
            nodeSelector:
              cloud.google.com/compute-class: ci-worker
