apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: publisher-health-check-policy
spec:
  default:
    config:
      httpHealthCheck:
        port: 80
        requestPath: /healthz
      type: HTTP
  targetRef:
    group: ""
    kind: Service
    name: publisher
