apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: httproute-auth-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: ee-gcp-sm
  target:
    name: httproute-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: ".htpasswd"
      remoteRef:
        key: cloudevents-basic-auth
