apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cs
resources:
  - namespace.yaml
  - kafka
  - external-secret.yaml
  - external-secret-httproute-auth.yaml
  - http-route.yaml
  - release.yaml
