apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: set-node-selector-tekton-taskrun-pods
spec:
  rules:
    - name: add-compute-class-and-annotations
      match:
        resources:
          kinds:
            - Pod
          selector:
            matchExpressions:
              - key: tekton.dev/taskRun
                operator: Exists
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
          spec:
            nodeSelector:
              cloud.google.com/compute-class: ci-worker
