apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secret-config.yaml
  - external-secrets/image-release-cred.yaml
  - external-secrets/oidc-secret.yaml
  - release.yaml
  - security-policy.yaml
  - reference-grant-ee-portal.yaml
