apiVersion: v1
kind: ConfigMap
metadata:
  name: cargo-mirror
immutable: true
data:
  config.toml: |
    [http]
    timeout = 600

    [source.crates-io]
    replace-with = "kellnr-cratesio"

    [source.kellnr-cratesio]
    registry = "sparse+http://kellnr.cache.svc:8000/api/v1/cratesio/"
