apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prow-jenkins-operator-0-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: prow-jenkins-operator-0-auth
    creationPolicy: Owner
  dataFrom:
    - extract:
        # json object contains keys: `user`, `token`, `url`
        key: gcp_prow_jenkins_operator_0_auth_json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prow-jenkins-operator-1-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: prow-jenkins-operator-1-auth
    creationPolicy: Owner
  dataFrom:
    - extract:
        # json object contains keys: `user`, `token`, `url`
        key: gcp_prow_jenkins_operator_1_auth_json
