apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prow-kubeconfig
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: prow-kubeconfig
    creationPolicy: Owner
  data:
    - secretKey: config
      remoteRef:
        key: gcp_prow_external_cluster_kce_kubeconfig
