apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-target-stores/gh-environments.yaml
  - 01-source-secrets/es-src-homebrew-tap-github-app-id.yaml
  - 01-source-secrets/es-src-homebrew-tap-github-app-private-key.yaml
  - 01-source-secrets/es-src-lakesql-release-s3-bundle.yaml
  - 02-deliveries/ps-homebrew-tap-github-app-id-release-homebrew.yaml
  - 02-deliveries/ps-homebrew-tap-github-app-private-key-release-homebrew.yaml
  - 02-deliveries/ps-lakesql-package-apk-passphrase-release-s3.yaml
  - 02-deliveries/ps-lakesql-package-apk-private-key-b64-release-s3.yaml
  - 02-deliveries/ps-lakesql-package-apk-public-key-b64-release-s3.yaml
  - 02-deliveries/ps-lakesql-package-gpg-passphrase-release-s3.yaml
  - 02-deliveries/ps-lakesql-package-gpg-private-key-b64-release-s3.yaml
