apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docs-cn
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: docs-cn
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: gcp_prow_docs_cn_s3_json # json object
