apiVersion: v1
kind: Service
metadata:
  name: {{ include "bazel-remote.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bazel-remote.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
{{- with .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
{{- end }}
  selector:
    {{- include "bazel-remote.selectorLabels" . | nindent 4 }}
