apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ats-storage
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 922Gi
  storageClassName: openebs-single-replica
  volumeMode: Filesystem
