prow:
  domainName: prow.test.io
jenkinsOperator:
  enabled: true
  instances:
    - name: default
      additionalArgs: []
      replicaCount: 1
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 100
        targetCPUUtilizationPercentage: 80
      resources: {}
      kubeconfigSecret: ""
      dryRun: true
      skipReport: false
      jenkinsUrl: http://jenkins-proxy
      csrfProtect: false
      auth:
        secretName: prow-jenkins
        secretKeyJenkinsUser: jenkins-admin-user
        secretKeyJenkinsToken: jenkins-admin-password
        secretKeyJenkinsBearerToken: ""
        secretKeyCert: ""
        secretKeyKey: ""
        secretKeyCaCert: ""
      config:
        maxConcurrency: 100
        maxGoroutines: 10
      labelSelector: ""
hook:
  additionalEnv:
    - name: FOO
      value: BAR
thirdPlugins:
  needs-rebase:
    additionalEnv:
      - name: FOO
        value: BAR
    args:
      - --dry-run=false
      - --github-app-id=$(GITHUB_APP_ID)
      - --github-app-private-key-path=/etc/github/app-private-key
      - --plugin-config=/etc/prow-plugin/plugins.yaml
      - --github-endpoint=http://prow-ghproxy
      - --github-graphql-endpoint=http://prow-ghproxy/graphql
      - --update-period=5m
    image:
      repository: gcr.io/k8s-prow/needs-rebase
      pullPolicy: Always
    ports:
      http: 8888
    service:
      type: ClusterIP
      port: 80
