apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: jenkins-worker-bigdisk
spec:
  nodePoolAutoCreation:
    enabled: true
  whenUnsatisfiable: ScaleUpAnyway
  priorities:
    # --------- spot types -----------
    - machineType: c4d-standard-16
      spot: true
      storage:
        bootDiskType: hyperdisk-balanced
        bootDiskSize: 500
    - machineType: c4-standard-16
      spot: true
      storage:
        bootDiskType: hyperdisk-balanced
        bootDiskSize: 500

    # --------- on-demand types -----------
    - machineType: c4d-standard-16
      spot: false
      storage:
        bootDiskType: hyperdisk-balanced
        bootDiskSize: 500
    - machineType: c4-standard-16
      spot: false
      storage:
        bootDiskType: hyperdisk-balanced
        bootDiskSize: 500
