apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: run-with-autopilot-spot-pod
spec:
  rules:
    - name: add-compute-class
      match:
        resources:
          kinds:
            - Pod
      mutate:
        patchStrategicMerge:
          spec:
            nodeSelector:
              cloud.google.com/compute-class: autopilot-spot
