apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - envoy-security-policies.yaml
  - publisher.yaml
  - worker-tiup-fileserver.yaml
  - worker-tiup-prod.yaml
  - worker-tiup-staging.yaml
  - publisher-ext-http-routes.yaml
