apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-agent.yaml
  - prod/release.yaml
  - prod/http-routes.yaml
  - staging/release.yaml
  - staging/http-routes.yaml
secretGenerator:
  - name: jenkins-release-values
    files:
      - prod-values1.yaml=prod/values-controller.yaml
      - prod-values2.yaml=prod/values-controller-plugins.yaml
      - prod-values3.yaml=prod/values-JCasC.yaml
      - prod-values4.yaml=prod/values-rbac.yaml
      - prod-values5.yaml=prod/values-agent.yaml
      - staging-values1.yaml=staging/values-controller.yaml
      - staging-values2.yaml=staging/values-controller-plugins.yaml
      - staging-values3.yaml=staging/values-JCasC.yaml
      - staging-values4.yaml=staging/values-rbac.yaml
      - staging-values5.yaml=staging/values-agent.yaml
configurations:
  - kustomize-config.yaml
