apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: set-application-node-selectors
  namespace: publisher
spec:
  rules:
    - name: set-compute-class
      match:
        resources:
          kinds:
            - Pod
      exclude:
        resources:
          kinds:
            - Pod
          selector:
            matchLabels:
              app.kubernetes.io/name: publisher
      mutate:
        patchStrategicMerge:
          spec:
            nodeSelector:
              cloud.google.com/compute-class: ee-application

    - name: set-publisher-node-selector
      match:
        resources:
          kinds:
            - Pod
          selector:
            matchLabels:
              app.kubernetes.io/name: publisher
      mutate:
        patchStrategicMerge:
          spec:
            nodeSelector:
              cloud.google.com/gke-nodepool: whitelist-nat
            tolerations:
              - effect: NoSchedule
                key: network
                value: whitelist
