apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: publisher
resources:
  - 00-namespace.yaml
  - 01-policies.yaml
  - external-secrets
  - publisher-packages-config.yaml
  - redis
  - releases.yaml
