---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: artifacts
spec:
  interval: 5m0s
  ref:
    branch: main
  url: https://github.com/PingCAP-QE/artifacts.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: publisher-packages-config
spec:
  targetNamespace: publisher
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: artifacts
  path: ./packages
  prune: true
