apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cache
  - cluster-policies
  - kafka
  - cloudevents-server
  - jenkins
  - jenkins-agents
  - tibuild
  - tekton
  - zot
  - prow-worker
