apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: ci-worker
spec:
  template:
    metadata:
      labels:
        compute-class: ci-worker
    spec:
      expireAfter: 168h
      nodeClassRef:
        group: karpenter.k8s.tke
        kind: TKEMachineNodeClass
        name: ci-worker
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: karpenter.k8s.tke/instance-family
          operator: In
          values:
            - C6
            - C5
            - SK1
            - S6
            - S5
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 5m
