## You should run it firstly:
## kubectl port-forward -n ee-cd svc/el-trigger-groups-listener 8080

### tikv/pd: push on master branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/master",
    "before": "a1a1eea8dafd7918d583378790a4bb6c39a21f97",
    "after": "3191594c91775dbf4679f48dda63a74d1de43176",
    "ref_type": "branch",
    "repository": {
        "name": "pd",
        "clone_url": "https://github.com/tikv/pd.git",
        "owner": {
            "login": "tikv"
        }
    }
}

### tikv/tikv: push on master branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/master",
    "before": "00000000000000000000000000000000000000000",
    "after": "86d4a49848cd920e081c2cf0249977149835d1c5",
    "ref_type": "branch",
    "repository": {
        "name": "tikv",
        "clone_url": "https://github.com/tikv/tikv.git",
        "owner": {
            "login": "tikv"
        }
    }
}

### pingcap/tiflow: push on master branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/master",
    "before": "00000000000000000000000000000000000000000",
    "after": "5921050d905001cddb3fdbe22949d121869243d4",
    "ref_type": "branch",
    "repository": {
        "name": "tiflow",
        "clone_url": "https://github.com/pingcap/tiflow.git",
        "owner": {
            "login": "pingcap"
        }
    }
}

### pingcap/tidb: push on master branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/master",
    "before": "00000000000000000000000000000000000000000",
    "after": "90628349860718bb84c94fe7dc1e1f9bd9da4348",
    "ref_type": "branch",
    "repository": {
        "name": "tidb",
        "clone_url": "https://github.com/pingcap/tidb.git",
        "owner": {
            "login": "pingcap"
        }
    }
}

### pingcap/tiflash: push on master branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/master",
    "before": "00000000000000000000000000000000000000000",
    "after": "f246f350923eb27e1dcfd271b7792481d5551bce",
    "ref_type": "branch",
    "repository": {
        "name": "tiflash",
        "clone_url": "https://github.com/pingcap/tiflash.git",
        "owner": {
            "login": "pingcap"
        }
    }
}

### pingcap/advanced-statefulset: push on master branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/master",
    "before": "00000000000000000000000000000000000000000",
    "after": "00595b4ef4ac4f08e16c930994ccc611c7ee6c64",
    "ref_type": "branch",
    "repository": {
        "name": "advanced-statefulset",
        "clone_url": "https://github.com/pingcap/advanced-statefulset.git",
        "owner": {
            "login": "pingcap"
        }
    }
}

########################
### pingcap/advanced-statefulset: create a new version tag
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: create

{
  "ref": "v0.5.1-alpha.1",
  "ref_type": "tag",
  "repository": {
    "name": "advanced-statefulset",
    "clone_url": "https://github.com/pingcap/advanced-statefulset.git",
    "owner": {
      "login": "pingcap"
    }
  }
}

########################
### push image tags on harbor
POST http://127.0.0.1:8080 HTTP/1.1
Content-Type: application/json

{
    "type": "PUSH_ARTIFACT",
    "occur_at": 1701143709,
    "operator": "wuhui.zuo",
    "event_data": {
        "resources": [
            {
                "digest": "sha256:c80bf3f0ad847433fe891b1bfb63425346a25633ff6dafbab2bc8ac7d14a6c3e",
                "tag": "master-00595b4-release_linux_amd64",
                "resource_url": "hub.pingcap.net/pingcap/advanced-statefulset:master-00595b4-release_linux_amd64"
            }
        ],
        "repository": {
            "date_created": 1699859083,
            "name": "advanced-statefulset",
            "namespace": "pingcap",
            "repo_full_name": "pingcap/advanced-statefulset",
            "repo_type": "public"
        }
    }
}
