apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ci-registry-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: ci-registry-auth
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .data }}"
  data:
    - secretKey: data
      remoteRef:
        key: ci_registry_auth_dockerconfig_json
