apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - externalsecret-ci-registry-auth.yaml
  - policies/inject-ci-labels.yaml
  - policies/set-pod-compute-class.yaml
  - policies/inject-registry-config.yaml
