apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudevents-server-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ee-gcp-sm
  target:
    name: cloudevents-server-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        config.yaml: |
          test_case_run:
            store:
              driver: mysql
              dsn: "{{ .test_case_run_dsn }}?tls=true&parseTime=true&loc=Asia%2FShanghai"
          tekton:
            lark:
              app_id: {{ .tekton_notify_lark_app_id }}
              app_secret: {{ .tekton_notify_lark_app_secret }}
            dashboard_base_url: http://tekton-dashboard.tekton-pipelines.svc:9097
            failed_step_tail_lines: 10
            notifications:
              - receivers: [{{ .tekton_notify_lark_default_channel }}]
              - event_type: dev.tekton.event.pipelinerun.failed.v1
                receivers: [{{ .tekton_notify_lark_pipelinerun_failed_channel }}, {{ .tekton_notify_lark_focus_failed_channel }}]
              - event_type: dev.tekton.event.taskrun.failed.v1
                receivers: [{{ .tekton_notify_lark_taskrun_failed_channel }}]
              # notify when tiup publish failed
              - event_type: dev.tekton.event.taskrun.failed.v1
                event_subject_reg: ^publish-tiup-from-oci-artifact
                receivers: [{{ .tekton_notify_lark_focus_failed_channel }}]
              # notify when image deliver external failed
              - event_type: dev.tekton.event.taskrun.failed.v1
                event_subject_reg: ^pingcap-deliver-image
                receivers: [{{ .tekton_notify_lark_focus_failed_channel }}]
          kafka:
            brokers:
              - cluster-cd-kafka-bootstrap.kafka.svc:9092
            client_id: cloudevents-server
            # authentication:
            #   mechanism: SCRAM-SHA-256
            #   user: username
            #   password: password
            producer:
              topic_mapping:
                dev.cdevents.pipelinerun.finished.0.1.0: jenkins-event
              default_topic: cloudevents-default-channel
            consumer:
              group_id: cloudevents-server-workers
              topic_mapping:
                "*": cloudevents-default-channel
              dead_letter_topic: cloudevents-dead-letter

  data:
    - secretKey: test_case_run_dsn
      remoteRef:
        key: tencentcloud_test_case_run_dsn
  dataFrom:
    - extract:
        # json object contains:
        #  - app_id
        #  - app_secret
        #  - default_channel
        #  - pipelinerun_failed_channel
        #  - taskrun_failed_channel
        #  - focus_failed_channel
        key: tekton_notify_lark_json
      rewrite:
        - regexp:
            source: "(.*)"
            target: "tekton_notify_$1"
