#yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/kyverno/refs/heads/main/config/crds/crds/policies.kyverno.io_namespacedmutatingpolicies.yaml
apiVersion: policies.kyverno.io/v1
kind: NamespacedMutatingPolicy
metadata:
  name: inject-registry-config
spec:
  evaluation:
    admission:
      enabled: true
    mutateExisting:
      enabled: false
  matchConditions:
    - name: is-pod
      expression: object.kind == 'Pod'
    - name: has-utils-container
      expression: object.spec.containers.exists(c, c.name == 'utils')
  matchConstraints:
    objectSelector:
      matchExpressions:
        - key: kubernetes.jenkins.io/controller
          operator: Exists
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
  mutations:
    - patchType: ApplyConfiguration
      applyConfiguration:
        expression: |
          Object{
            spec: Object.spec{
              volumes: [Object.spec.volumes{name: "ci-registry-auth", secret: Object.spec.volumes.secret{secretName: "ci-registry-auth", defaultMode: 292}}],
              containers: [Object.spec.containers{name: "utils", volumeMounts: [Object.spec.containers.volumeMounts{mountPath: "/var/run/ci/registry", name: "ci-registry-auth", readOnly: true}], env: [Object.spec.containers.env{name: "DOCKER_CONFIG", value: "/var/run/ci/registry"}]}]
            }
          }
    - patchType: JSONPatch
      jsonPatch:
        expression: |
          object.spec.?volumes.orValue([]).map(v, v.?name.orValue('') == 'ci-registry-auth' ? 1 : 0).indexOf(1) < 0 ||
          object.spec.volumes[object.spec.volumes.map(v, v.name == 'ci-registry-auth' ? 1 : 0).indexOf(1)].?secret.orValue({}).?items.orValue([]).size() > 0 ?
          [] :
          [JSONPatch{op: "add", path: "/spec/volumes/" + string(object.spec.volumes.map(v, v.name == 'ci-registry-auth' ? 1 : 0).indexOf(1)) + "/secret/items", value: [{"key": ".dockerconfigjson", "path": "config.json"}]}]
