apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - source-envoyproxy.yaml
  - source-envoy-gateway-upstream.yaml
  - crds-kustomization.yaml
  - release-envoy-gateway.yaml
