apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: envoy-gateway-upstream
  namespace: infra
spec:
  interval: 1h
  url: https://github.com/envoyproxy/gateway
  ref:
    tag: v1.9.0-rc.1
