## You should run it firstly:
## kubectl port-forward -n ee-cd svc/el-public 8080



########################
### push image tags on harbor
POST http://127.0.0.1:8080 HTTP/1.1
Content-Type: application/json

{
    "type": "PUSH_ARTIFACT",
    "occur_at": 1701143709,
    "operator": "wuhui.zuo",
    "event_data": {
        "resources": [
            {
                "digest": "sha256:c80bf3f0ad847433fe891b1bfb63425346a25633ff6dafbab2bc8ac7d14a6c3e",
                "tag": "master-00595b4-release_linux_amd64",
                "resource_url": "hub.pingcap.net/pingcap/advanced-statefulset:master-00595b4-release_linux_amd64"
            }
        ],
        "repository": {
            "date_created": 1699859083,
            "name": "advanced-statefulset",
            "namespace": "pingcap",
            "repo_full_name": "pingcap/advanced-statefulset",
            "repo_type": "public"
        }
    }
}

### push image tags on harbor - tiproxy trunk branch
POST http://127.0.0.1:8080 HTTP/1.1
Content-Type: application/json

{
    "type": "PUSH_ARTIFACT",
    "occur_at": 1701143709,
    "operator": "wuhui.zuo",
    "event_data": {
        "resources": [
            {
                "digest": "sha256:965cc820c2c72614f885b7bb2f2a78369c80a9850a5441972436d86ad4019b46",
                "tag": "main",
                "resource_url": "hub.pingcap.net/pingcap/tiproxy/image:main"
            }
        ],
        "repository": {
            "date_created": 1699859083,
            "name": "tiproxy/image",
            "namespace": "pingcap",
            "repo_full_name": "pingcap/tiproxy/image",
            "repo_type": "public"
        }
    }
}
