## You should run it firstly:
## kubectl port-forward -n ee-cd svc/el-public 8080

### tikv/pd: push on master branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/master",
    "before": "a1a1eea8dafd7918d583378790a4bb6c39a21f97",
    "after": "3191594c91775dbf4679f48dda63a74d1de43176",
    "ref_type": "branch",
    "repository": {
        "name": "pd",
        "clone_url": "https://github.com/tikv/pd.git",
        "owner": {
            "login": "tikv"
        }
    }
}

### tikv/tikv: push on master branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/master",
    "before": "00000000000000000000000000000000000000000",
    "after": "86d4a49848cd920e081c2cf0249977149835d1c5",
    "ref_type": "branch",
    "repository": {
        "name": "tikv",
        "clone_url": "https://github.com/tikv/tikv.git",
        "owner": {
            "login": "tikv"
        }
    }
}

### pingcap/tiflow: push on master branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/master",
    "before": "00000000000000000000000000000000000000000",
    "after": "5921050d905001cddb3fdbe22949d121869243d4",
    "ref_type": "branch",
    "repository": {
        "name": "tiflow",
        "clone_url": "https://github.com/pingcap/tiflow.git",
        "owner": {
            "login": "pingcap"
        }
    }
}

### pingcap/tidb: push on master branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/master",
    "before": "00000000000000000000000000000000000000000",
    "after": "c52655cd198b11cd0fae18d6d7b9305ad74783ee",
    "ref_type": "branch",
    "repository": {
        "name": "tidb",
        "clone_url": "https://github.com/pingcap/tidb.git",
        "owner": {
            "login": "pingcap"
        }
    }
}

### pingcap/tiflash: push on master branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/master",
    "before": "00000000000000000000000000000000000000000",
    "after": "f246f350923eb27e1dcfd271b7792481d5551bce",
    "ref_type": "branch",
    "repository": {
        "name": "tiflash",
        "clone_url": "https://github.com/pingcap/tiflash.git",
        "owner": {
            "login": "pingcap"
        }
    }
}

### pingcap/advanced-statefulset: push on master branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/master",
    "before": "00000000000000000000000000000000000000000",
    "after": "00595b4ef4ac4f08e16c930994ccc611c7ee6c64",
    "ref_type": "branch",
    "repository": {
        "name": "advanced-statefulset",
        "clone_url": "https://github.com/pingcap/advanced-statefulset.git",
        "owner": {
            "login": "pingcap"
        }
    }
}

########################
### pingcap/advanced-statefulset: create a new version tag
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: create

{
  "ref": "v0.5.1-alpha.1",
  "ref_type": "tag",
  "repository": {
    "name": "advanced-statefulset",
    "clone_url": "https://github.com/pingcap/advanced-statefulset.git",
    "owner": {
      "login": "pingcap"
    }
  }
}


### pingcap/tiproxy push on main branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/main",
    "before": "00000000000000000000000000000000000000000",
    "after": "b1d210fa8a61abcba293aea2b2adfca1793b353f",
    "ref_type": "branch",
    "repository": {
        "name": "tiproxy",
        "clone_url": "https://github.com/pingcap/tiproxy",
        "owner": {
            "login": "pingcap"
        }
    }
}

### pingcap/tidb-binlog push on master branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/master",
    "before": "00000000000000000000000000000000000000000",
    "after": "154d6d99d8bda586e10723c3aacc6c4d8ff6a1c6",
    "ref_type": "branch",
    "repository": {
        "name": "tidb-binlog",
        "clone_url": "https://github.com/pingcap/tidb-binlog",
        "owner": {
            "login": "pingcap"
        }
    }
}

### pingcap/tidb-binlog version tag created
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: create

{
  "ref": "v7.5.0",
  "ref_type": "tag",
  "repository": {
    "name": "tidb-binlog",
    "clone_url": "https://github.com/pingcap/tidb-binlog.git",
    "owner": {
      "login": "pingcap"
    }
  }
}

### pingcap/tidb-tools push on master branch
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/master",
    "before": "00000000000000000000000000000000000000000",
    "after": "c4bdf178b3d6ae0242332aa7ef8448b74eb5b45c",
    "ref_type": "branch",
    "repository": {
        "name": "tidb-tools",
        "clone_url": "https://github.com/pingcap/tidb-tools",
        "owner": {
            "login": "pingcap"
        }
    }
}

### pingcap/tidb-tools version tag created
POST http://127.0.0.1:8080 HTTP/1.1
Accept: */*
content-type: application/json
X-GitHub-Event: create

{
  "ref": "v7.5.0",
  "ref_type": "tag",
  "repository": {
    "name": "tidb-tools",
    "clone_url": "https://github.com/pingcap/tidb-tools.git",
    "owner": {
      "login": "pingcap"
    }
  }
}
