# default prow config generated by helm release.
prowjob_namespace: {{ .Release.Namespace }}
pod_namespace: {{ .Values.prow.podsNamespace }}

in_repo_config:
  enabled:
    "*": true

deck:
  spyglass:
    lenses:
    - lens:
        name: metadata
      required_files:
      - started.json|finished.json
    - lens:
        config:
        name: buildlog
      required_files:
      - build-log.txt
    - lens:
        name: junit
      required_files:
      - .*/junit.*\.xml
    - lens:
        name: podinfo
      required_files:
      - podinfo.json
  {{- if .Values.jenkinsOperator.enabled }}
  external_agent_logs:
  - agent: jenkins    
    url_template: 'http://{{ include "prow.fullname.jenkinsoperator" . }}/job/{{`{{.Spec.Job}}/{{.Status.JenkinsBuildID}}/consoleText`}}'
  {{- end }}
plank:
  job_url_prefix_config:
    "*": https://{{ .Values.prow.domainName }}/view/
  report_templates:
    '*': >-
        [Full PR test history](https://{{ .Values.prow.domainName }}/pr-history?{{`org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end }}`}}).
        [Your PR dashboard](https://{{ .Values.prow.domainName }}/pr?query=is:pr+state:open+author:{{`{{with index .Spec.Refs.Pulls 0}}{{.Author}}{{end }}`}}).
  default_decoration_configs:
    "*":
      gcs_configuration:
        bucket: {{ include "prow.persistent.scheme" . }}://prow-logs
        path_strategy: explicit
      {{- if .Values.persistent.credentials }}{{- if contains .Values.persistent.type "gcs s3" }}
      {{ .Values.persistent.type }}_credentials_secret: {{ include "prow.fullname" . }}-{{ .Values.persistent.type }}-credentials
      {{- end }}{{- end }}
      utility_images:
        clonerefs: gcr.io/k8s-prow/clonerefs:{{ .Chart.AppVersion }}
        entrypoint: gcr.io/k8s-prow/entrypoint:{{ .Chart.AppVersion }}
        initupload: gcr.io/k8s-prow/initupload:{{ .Chart.AppVersion }}
        sidecar: gcr.io/k8s-prow/sidecar:{{ .Chart.AppVersion }}

tide:
  queries:
  - labels:
      - lgtm
      - approved
    missingLabels:
      - needs-rebase
      - do-not-merge/hold
      - do-not-merge/work-in-progress
      - do-not-merge/invalid-owners-file
    {{- if .Values.prow.githubOrg }}
    orgs:
      - {{ .Values.prow.githubOrg }}
    {{- else }}
    orgs: []
    {{- end }}

decorate_all_jobs: true

jenkins_operators:
  - max_concurrency: {{ .Values.jenkinsOperator.config.maxConcurrency }}
    max_goroutines: {{ .Values.jenkinsOperator.config.maxGoroutines }}
    job_url_template: >-
        https://{{ .Values.prow.domainName }}/view/{{ include "prow.persistent.scheme" . }}/prow-logs/{{`{{if eq .Spec.Type "presubmit"}}pr-logs/pull{{else if eq .Spec.Type "batch"}}pr-logs/pull{{else}}logs{{end}}{{if ne .Spec.Refs.Repo "origin"}}/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}{{end}}{{if eq .Spec.Type "presubmit"}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else if eq .Spec.Type "batch"}}/batch{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}`}}/
    report_templates:
      '*': >-
          [Full PR test history](https://{{ .Values.prow.domainName }}/pr-history?{{`org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end }}`}}).