#yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/kyverno/refs/heads/main/config/crds/policies.kyverno.io/policies.kyverno.io_mutatingpolicies.yaml
apiVersion: policies.kyverno.io/v1
kind: MutatingPolicy
metadata:
  name: make-application-pods-run-on-low-cost-nodes
spec:
  evaluation:
    admission:
      enabled: true
    mutateExisting:
      enabled: false
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
  matchConditions:
    - name: is-application-namespace
      expression: "object.metadata.namespace in ['cs', 'jenkins', 'kafka', 'kafka-operator', 'tekton-operator', 'tekton-pipelines', 'tibuild', 'ee-cd', 'publisher', 'jenkins-agents']"
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: |
          has(object.spec.nodeSelector) ?
          [
            JSONPatch{
              op: "add",
              path: "/spec/nodeSelector/compute-class",
              value: "ee-application"
            }
          ] :
          [
            JSONPatch{
              op: "add",
              path: "/spec/nodeSelector",
              value: {"compute-class": "ee-application"}
            }
          ]
    - patchType: JSONPatch
      jsonPatch:
        expression: |
          object.spec.containers.map(c, i,
            has(c.resources) && has(c.resources.requests) && has(c.resources.requests.cpu) ?
            null :
            (
              has(c.resources) ?
              JSONPatch{
                op: "add",
                path: sprintf("/spec/containers/%d/resources/requests", [i]),
                value: {"cpu": "100m", "memory": "200Mi"}
              } :
              JSONPatch{
                op: "add",
                path: sprintf("/spec/containers/%d/resources", [i]),
                value: {"requests": {"cpu": "100m", "memory": "200Mi"}}
              }
            )
          ).filter(p, p != null)
