apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-src-maven-central-token-username
  namespace: github-actions-secrets
  labels:
    ee.pingcap.com/owner-team: platform
    ee.pingcap.com/managed-by: fluxcd
    ee.pingcap.com/github-org: tidbcloud
  annotations:
    ee.pingcap.com/source-secret-id: gha__env__tidbcloud__lake-jdbc__maven-central-com-tidbcloud-release__maven_central_token_username
    ee.pingcap.com/github-secret-name: MAVEN_CENTRAL_TOKEN_USERNAME
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-sm-github-actions
    kind: SecretStore
  target:
    name: src-maven-central-token-username
    creationPolicy: Owner
  data:
    - secretKey: value
      remoteRef:
        key: gha__env__tidbcloud__lake-jdbc__maven-central-com-tidbcloud-release__maven_central_token_username
