apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-artifact-s3
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: jenkins-artifact-s3
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          jenkins.io/credentials-type: aws
        annotations:
          jenkins.io/credentials-description: AWS credentials for bucket to store Jenkins artifacts
      data:
        accessKey: "{{ .accessKey }}"
        secretKey: "{{ .accessSecret }}"
  dataFrom:
    - extract:
        key: "${JENKINS_CACHE_S3_JSON}"
