apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tirelease-secret-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: tirelease-secret-config
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: tirelease_secret_json
