apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tirelease
images:
  - name: hub.pingcap.net/ee/tirelease
    newTag: 5c919a3-dirty-amd64
resources:
  - namespace.yaml
  - configmaps.yaml
  - external-secret.yaml
  - deployment.yaml
  - jobs-deployment.yaml
  - webhook-deployment.yaml
  - service.yaml
  - httproute.yaml
