apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: external-https-proxy
  namespace: infra
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        annotations:
          service.cloud.tencent.com/security-groups: "${security_group_id}"
          service.cloud.tencent.com/pass-to-target: "true"
          service.cloud.tencent.com/direct-access: 'true'
