apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: external-https-proxy
  namespace: infra
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        annotations:
          tke.endpoint.security-group: "${security_group_id}"
