---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docs-cn-aws-ak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: docs-cn-aws-ak
    creationPolicy: Owner
    template:
      metadata:
        labels:
          jenkins.io/credentials-type: secretText
          jenkins.io/credentials-scope: GLOBAL
  data:
    - secretKey: text
      remoteRef:
        key: prod2_jenkins_beta_docs_cn_s3_json
        property: aws-ak
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docs-cn-aws-sk
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: docs-cn-aws-sk
    creationPolicy: Owner
    template:
      metadata:
        labels:
          jenkins.io/credentials-type: secretText
          jenkins.io/credentials-scope: GLOBAL
  data:
    - secretKey: text
      remoteRef:
        key: prod2_jenkins_beta_docs_cn_s3_json
        property: aws-sk
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docs-cn-aws-region
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: docs-cn-aws-region
    creationPolicy: Owner
    template:
      metadata:
        labels:
          jenkins.io/credentials-type: secretText
          jenkins.io/credentials-scope: GLOBAL
  data:
    - secretKey: text
      remoteRef:
        key: prod2_jenkins_beta_docs_cn_s3_json
        property: aws-region
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docs-cn-aws-bn
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: docs-cn-aws-bn
    creationPolicy: Owner
    template:
      metadata:
        labels:
          jenkins.io/credentials-type: secretText
          jenkins.io/credentials-scope: GLOBAL
  data:
    - secretKey: text
      remoteRef:
        key: prod2_jenkins_beta_docs_cn_s3_json
        property: aws-bn
