---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: codecov-token-tidb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: codecov-token-tidb
    creationPolicy: Owner
    template:
      metadata:
        labels:
          jenkins.io/credentials-type: secretText
          jenkins.io/credentials-scope: GLOBAL
  data:
    - secretKey: text
      remoteRef:
        key: tencentcloud_jenkins_codecov_tokens_json
        property: tidb
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: codecov-token-tikv-migration
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: codecov-token-tikv-migration
    creationPolicy: Owner
    template:
      metadata:
        labels:
          jenkins.io/credentials-type: secretText
          jenkins.io/credentials-scope: GLOBAL
  data:
    - secretKey: text
      remoteRef:
        key: tencentcloud_jenkins_codecov_tokens_json
        property: tikv-migration
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: codecov-token-tiflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: codecov-token-tiflow
    creationPolicy: Owner
    template:
      metadata:
        labels:
          jenkins.io/credentials-type: secretText
          jenkins.io/credentials-scope: GLOBAL
  data:
    - secretKey: text
      remoteRef:
        key: tencentcloud_jenkins_codecov_tokens_json
        property: tiflow
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: codecov-token-tiproxy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: codecov-token-tiproxy
    creationPolicy: Owner
    template:
      metadata:
        labels:
          jenkins.io/credentials-type: secretText
          jenkins.io/credentials-scope: GLOBAL
  data:
    - secretKey: text
      remoteRef:
        key: tencentcloud_jenkins_codecov_tokens_json
        property: tiproxy
