apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
secretGenerator:
  - name: jenkins-cbg-values
    files:
      - values1.yaml=values-controller.yaml
      - values2.yaml=values-controller-plugins.yaml
      - values3.yaml=values-persistence.yaml
      - values4.yaml=values-agent.yaml
      - values5.yaml=values-rbac.yaml
      - values6.yaml=values-service-account.yaml
      - values7.yaml=values-JCasC.yaml
configMapGenerator:
  - name: jenkins-cbg-init-scripts
    options:
      disableNameSuffixHash: true
    files:
      - fix-hotcopy-k8s-cloud.sh=files/fix-hotcopy-k8s-cloud.sh
configurations:
  - kustomize-config.yaml
