apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-sm-github-actions
  namespace: github-actions-secrets
  labels:
    ee.pingcap.com/owner-team: platform
    ee.pingcap.com/managed-by: fluxcd
spec:
  provider:
    gcpsm:
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: gcp-sm-github-actions
      projectID: pingcap-testing-account
