apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: limit-pods-run-on-t2d-ondemand-nodes
spec:
  rules:
    - name: restrict-non-el-pods-to-c4-c4a
      match:
        resources:
          kinds:
            - Pod
      mutate:
        patchStrategicMerge:
          spec:
            nodeSelector:
              cloud.google.com/compute-class: ee-application
