apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gatewayclass.yaml
  - gateway-internal.yaml
  - gateway-public.yaml
  - client-traffic-policy-internal.yaml
  - client-traffic-policy-jenkins-escaped-slashes.yaml
  - es-gateway-tls-certs.yaml
