apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # renovate: datasource=github-releases depName=tektoncd/operator versioning=semver
  - https://github.com/tektoncd/operator/releases/download/v0.77.0/release.yaml
  - operator-config.yaml
  - operator-manual-approval-gate.yaml

  - httproute-dashboard.yaml
  - cm-config-events.yaml
  # renovate: datasource=github-releases depName=tektoncd/operator versioning=semver
  - https://cdn.jsdelivr.net/gh/tektoncd/pipeline@v1.3.1/optional_config/enable-log-access-to-controller/clusterrole.yaml
  - https://cdn.jsdelivr.net/gh/tektoncd/pipeline@v1.3.1/optional_config/enable-log-access-to-controller/clusterrolebinding.yaml
