apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: v2-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ee-gcp-sm
  target:
    name: v2-config
    template:
      type: Opaque
      data:
        config.yaml: |
          store:
            driver: mysql
            dsn: {{ .dsn }}

          tekton:
            cloudevent_endpoint: http://cloudevents-server.cs.svc/events
            view_url: https://internal2-do.pingcap.net/tekton/#/namespaces/ee-cd/pipelineruns
            oci_file_download_url: "https://internal2-do.pingcap.net/dl/oci-file"

          github:
            token: {{ .github_token }}

          product_repo_map:
            pd: tikv/pd
            tikv: tikv/tikv
            tiflash: pingcap/tiflash
            tidb: pingcap/tidb
            ticdc: pingcap/ticdc
            dm: pingcap/tiflow

  data:
    - secretKey: github_token
      remoteRef:
        key: github-bot-token
    - secretKey: dsn
      remoteRef:
        key: prod2_tibuild_v2_dsn
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ingress-auth-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: ingress-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: auth
      remoteRef:
        key: tidbx-ops-client-tibuild-v2-basic-auth
