apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secret-config.yaml
  - external-secret-httproute-auth.yaml
  - release.yaml
  - ingress.yaml
  - http-route-v2-auth.yaml
