apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: v2
spec:
  chart:
    spec:
      chart: tibuild-v2
      version: 2.0.0-alpha.1
      sourceRef:
        kind: HelmRepository
        name: ee-apps
        namespace: flux-system
  interval: 5m
  timeout: 5m
  install:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
    recreate: true
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  test:
    enable: true
  values:
    replicaCount: 1
    resources:
      requests:
        cpu: "200m"
        memory: 256Mi
      limits:
        cpu: "500m"
        memory: 512Mi
    image:
      repository: ghcr.io/pingcap-qe/ee-apps/exp-tibuild-v2
      # renovate: datasource=docker depName=ghcr.io/pingcap-qe/ee-apps/exp-tibuild-v2 versioning=semver
      tag: v2026.3.15-6-g4dcf9b3
    server:
      debug: false
      config:
        secretName: v2-config
        secretKey: config.yaml
    serviceAccount:
      create: false
    httpRoute:
      enabled: true
      parentRefs:
        - kind: Gateway
          name: internal-gateway
          namespace: infra
      hostnames:
        - internal2-do.pingcap.net
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /tibuild/api/v2
          filters:
            - type: URLRewrite
              urlRewrite:
                path:
                  type: ReplacePrefixMatch
                  replacePrefixMatch: /api/v2
