apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: ps-homebrew-tap-github-app-client-id-release-homebrew
  labels:
    ee.pingcap.com/owner-team: platform
    ee.pingcap.com/managed-by: fluxcd
    ee.pingcap.com/github-org: tidbcloud
  annotations:
    ee.pingcap.com/github-secret-name: HOMEBREW_TAP_GITHUB_APP_CLIENT_ID
spec:
  deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRefs:
    - name: gh-env-tidbcloud-lakesql-release-homebrew
      kind: SecretStore
  selector:
    secret:
      name: src-homebrew-tap-github-app-client-id
  data:
    - match:
        secretKey: value
        remoteRef:
          remoteKey: HOMEBREW_TAP_GITHUB_APP_CLIENT_ID
