apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-sre-bot-ssh
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: github-sre-bot-ssh
    creationPolicy: Owner
    template:
      metadata:
        labels:
          jenkins.io/credentials-type: basicSSHUserPrivateKey
          jenkins.io/credentials-scope: GLOBAL
  data:
    - secretKey: privateKey
      remoteRef:
        key: github-bot-ssh-rsa-json
        property: ssh-privatekey
    - secretKey: username
      remoteRef:
        key: github-bot-username
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-bot-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: github-bot-token
    creationPolicy: Owner
    template:
      metadata:
        labels:
          jenkins.io/credentials-type: secretText
          jenkins.io/credentials-scope: GLOBAL
  data:
    - secretKey: text
      remoteRef:
        key: github-bot-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-pr-diff-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: github-pr-diff-token
    creationPolicy: Owner
    template:
      metadata:
        labels:
          jenkins.io/credentials-type: secretText
          jenkins.io/credentials-scope: GLOBAL
  data:
    - secretKey: text
      remoteRef:
        key: github-bot-token
