apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ks3util-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: ks3util-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          jenkins.io/credentials-type: secretFile
          jenkins.io/credentials-scope: GLOBAL
      data:
        filename: ks3util.conf
        data: "{{ .config }}"
  data:
    - secretKey: config
      remoteRef:
        key: "${KS3UTIL_CONFIG}"
