apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: github
    creationPolicy: Owner
  data:
    - secretKey: git-username
      remoteRef:
        key: github-bot-username
    - secretKey: bot-token
      remoteRef:
        key: github-bot-token
    - secretKey: pr-diff-token
      remoteRef:
        key: github-bot-token
    - secretKey: git-private-key
      remoteRef:
        key: github-bot-ssh-rsa-json
        property: ssh-privatekey
